name: build

permissions:
  contents: write

on:
  push:
    branches: [ main, fix-gh-ci ]
  pull_request:
    branches: [ main, fix-gh-ci ]
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxfixes-dev libxtst-dev libxinerama-dev libxext-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Create Linux artifact
        if: runner.os == 'Linux' && github.event_name == 'release'
        run: zip -j ScreenShotApp-linux-x64.zip build/ScreenShotApp

      - name: Create Windows artifact
        if: runner.os == 'Windows' && github.event_name == 'release'
        shell: pwsh
        run: Compress-Archive -Path "build/Release/ScreenShotApp.exe" -DestinationPath "ScreenShotApp-windows-x64.zip" -Force

      - name: Create macOS artifact
        if: runner.os == 'macOS' && github.event_name == 'release'
        run: zip -j ScreenShotApp-macos-x64.zip build/ScreenShotApp

      - name: Upload release artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: ScreenShotApp-${{ runner.os }}-x64
          path: ScreenShotApp-*.zip
          retention-days: 1

  release:
    name: Upload release assets to existing Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload Linux asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ScreenShotApp-Linux-x64/ScreenShotApp-linux-x64.zip
          asset_name: ScreenShotApp-linux-x64.zip
          asset_content_type: application/zip

      - name: Upload Windows asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ScreenShotApp-Windows-x64/ScreenShotApp-windows-x64.zip
          asset_name: ScreenShotApp-windows-x64.zip
          asset_content_type: application/zip

      - name: Upload macOS asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ScreenShotApp-macOS-x64/ScreenShotApp-macos-x64.zip
          asset_name: ScreenShotApp-macos-x64.zip
          asset_content_type: application/zip
